# a config for inference: https://opennmt.net/OpenNMT-py/options/translate.html

# path to model
model: /home/AK/skrjanec/text_simplification/models/4/rnn_basic_copy_step_450.pt

# path to the test set (one sequence per line)
src: /home/AK/skrjanec/text_simplification/data/apa/source_target_copy/source_test_level_tok_bin_lev_bin.txt 

# path to the output file - predictions
output: /home/AK/skrjanec/text_simplification/pred/4/rnn_basic_copy.txt

# decoding options
beam_size: 4

block_ngram_repeat: 2

gpu: 0
