## Where the samples will be written
save_data: /home/AK/skrjanec/text_simplification/vocabs/example
## Where the vocab(s) will be written
src_vocab: /home/AK/skrjanec/text_simplification/vocabs/shared_all_ct.txt
# sh_set_vocab.src
#tgt_vocab: /home/CE/skrjanec/chart_onmt/vocabs/sh_delex_vocab.tgt # if the vocab is shared, commeted out
# Prevent overwriting existing files in the folder
#overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /home/AK/skrjanec/text_simplification/data/apa/source_target_copy/source_train_level_char_bin_tok_bin_lev_bin.txt
        path_tgt: /home/AK/skrjanec/text_simplification/data/apa/source_target_copy/target_train.txt
    valid:
        path_src: /home/AK/skrjanec/text_simplification/data/apa/source_target_copy/source_val_level_char_bin_tok_bin_lev_bin.txt
        path_tgt: /home/AK/skrjanec/text_simplification/data/apa/source_target_copy/target_val.txt

share_vocab: True

