## Where the samples will be written
save_data: /home/AK/skrjanec/text_simplification/vocabs/example
## Where the vocab(s) will be written
src_vocab: /home/AK/skrjanec/text_simplification/vocabs/shared_no_ct.txt
# sh_set_vocab.src
#tgt_vocab: /home/CE/skrjanec/chart_onmt/vocabs/sh_delex_vocab.tgt # if the vocab is shared, commeted out
# Prevent overwriting existing files in the folder
#overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /home/AK/skrjanec/text_simplification/data/apa/source_target/source_none_train.txt
        path_tgt: /home/AK/skrjanec/text_simplification/data/apa/source_target/target_train.txt
    valid:
        path_src: /home/AK/skrjanec/text_simplification/data/apa/source_target/source_none_val.txt
        path_tgt: /home/AK/skrjanec/text_simplification/data/apa/source_target/target_val.txt

share_vocab: True

